name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=23.2.1
  - pyarrow=2.0
  - pip:
      - wandb==0.15.11
      - pandas-profiling==3.6.6