name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow<=1.14.1
  - ipython<=7.21.0
  - notebook<=7.0.3
  - jupyterlab<=4.0.6
  - cookiecutter<=1.7.2
  - hydra-core<=1.0.6
  - matplotlib<=3.3.4
  - pandas<=1.2.3
  - git<=2.30.2
  - pip=23.2.1
  - pip:
      - wandb==0.15.10
      - pandas-profiling==3.6.6

